services:
  web: 
    build: "."
    ports:
      - "3000:3000"
    volumes:
      - ".:/var/www/app"
    networks:
      - app
      - redis

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - PSQL_USERNAME=postgres
    ports:
      - "5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data"
    networks:
      - app

  redis:
    image: redis:latest
    networks:
      - redis

  promtail:
    image: grafana/promtail
    volumes: 
      - tmp/log:/var/log
      - volumes/promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=promtail.yml
    networks:
      - loki

volumes:
  database:
networks:
  app:
  redis:
  loki: