services:
  web: 
    build: "."
    ports:
      - "3000:3000"
    volumes:
      - ".:/var/www/app"
    networks:
      - app
      - redis

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - PSQL_USERNAME=postgres
    ports:
      - "5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data"
    networks:
      - app

  redis:
    image: redis:latest
    networks:
      - redis

  promtail:
    image: grafana/promtail
    volumes: 
      - ./tmp/log:/var/log
      - ./volumes/promtail:/etc/promtail
      - ./promtail.yml:/etc/promtail/promtail.yml
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - loki

  loki:
    image: grafana/loki
    volumes:
      - ./volumes/loki:/etc/loki
      - ./loki.yml:/etc/loki/loki.yml
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - loki

volumes:
  database:
networks:
  app:
  redis:
  loki: